services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
      - 8443:8443
    command: start-dev
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

volumes:
  keycloak-postgres:
