// <auto-generated />
namespace PRS_bootcamp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessageFKtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageFKtest));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191351277_Message FK test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
