CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Status" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(20) NOT NULL,
    CONSTRAINT "PK_Status" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(30) NOT NULL,
    "Password" character varying(30) NOT NULL,
    "FirstName" character varying(30) NOT NULL,
    "LastName" character varying(30) NOT NULL,
    "Phone" character varying(12),
    "Email" character varying(255),
    "IsAdmin" boolean NOT NULL,
    "IsReviewer" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Vendors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(30) NOT NULL,
    "Name" character varying(30) NOT NULL,
    "Address" character varying(30) NOT NULL,
    "City" character varying(30) NOT NULL,
    "State" character varying(2) NOT NULL,
    "Zip" character varying(5) NOT NULL,
    "Phone" character varying(12) NOT NULL,
    "Email" character varying(255) NOT NULL,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
);

CREATE TABLE "PurchaseRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(80) NOT NULL,
    "Justification" character varying(80) NOT NULL,
    "ReasonForRejection" character varying(80) NOT NULL,
    "DateNeeded" timestamp with time zone NOT NULL,
    "DeliveryMode" character varying(20) NOT NULL,
    "Status" character varying(10) NOT NULL,
    "Total" numeric(11,2) NOT NULL,
    "SubmittedDate" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_PurchaseRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorPartNumber" character varying(30) NOT NULL,
    "Name" character varying(30) NOT NULL,
    "Price" numeric(11,2) NOT NULL,
    "Unit" character varying(30) NOT NULL,
    "Photopath" character varying(255),
    "VendorId" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PurchaseRequestLineItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseRequestId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_PurchaseRequestLineItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseRequestLineItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PurchaseRequestLineItems_PurchaseRequests_PurchaseRequestId" FOREIGN KEY ("PurchaseRequestId") REFERENCES "PurchaseRequests" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Products_VendorId_VendorPartNumber" ON "Products" ("VendorId", "VendorPartNumber");

CREATE INDEX "IX_PurchaseRequestLineItems_ProductId" ON "PurchaseRequestLineItems" ("ProductId");

CREATE INDEX "IX_PurchaseRequestLineItems_PurchaseRequestId" ON "PurchaseRequestLineItems" ("PurchaseRequestId");

CREATE INDEX "IX_PurchaseRequests_UserId" ON "PurchaseRequests" ("UserId");

CREATE UNIQUE INDEX "IX_Users_UserName" ON "Users" ("UserName");

CREATE UNIQUE INDEX "IX_Vendors_Name" ON "Vendors" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240818191737_Initial', '8.0.8');

COMMIT;

