begin;

-- 1) Status lookup (stable, admin-editable)
create table request_status (
  id   smallserial primary key,
  code varchar(20) not null unique
);

insert into request_status(code)
values ('draft'),('submitted'),('approved'),('rejected');

-- 2) Minimal app_user (internal id + external id from IdP; no PII)
create table app_user (
  id           integer generated by default as identity,
  external_id  text not null,                 -- e.g., Keycloak "sub" claim
  is_admin     boolean not null default false,
  is_reviewer  boolean not null default false,
  constraint pk_app_user primary key (id),
  constraint uq_app_user__external_id unique (external_id)
);

-- 3) Vendors/products
create table vendor (
  id      integer generated by default as identity,
  code    varchar(30) not null,
  name    varchar(30) not null,
  address varchar(30) not null,
  city    varchar(30) not null,
  state   varchar(2)  not null,
  zip     varchar(5)  not null,
  phone   varchar(12) not null,
  email   varchar(255) not null,
  constraint pk_vendor primary key (id),
  constraint uq_vendor__code unique (code)
);

create table product (
  id                 integer generated by default as identity,
  vendor_part_number varchar(30) not null,
  name               varchar(30) not null,
  price              numeric(11,2) not null check (price >= 0),
  unit               varchar(30) not null,
  photo_path         varchar(255),
  vendor_id          integer not null,
  constraint pk_product primary key (id),
  constraint fk_product__vendor foreign key (vendor_id)
    references vendor (id) on delete restrict
);

create unique index ix_product__vendor_id_vendor_part_number
  on product (vendor_id, vendor_part_number);

-- 4) Purchase requests
create table purchase_request (
  id                  integer generated by default as identity,
  description         varchar(80) not null,
  justification       varchar(80) not null,
  reason_for_rejection varchar(80),
  date_needed         timestamptz not null,
  delivery_mode       varchar(20) not null,
  status_id           smallint not null,
  total               numeric(11,2) not null default 0 check (total >= 0),
  submitted_date      timestamptz not null default now(),
  user_id             integer not null,
  constraint pk_purchase_request primary key (id),
  constraint fk_pr__user foreign key (user_id)
    references app_user (id) on delete restrict,
  constraint fk_pr__status foreign key (status_id)
    references request_status (id)
);

create index ix_purchase_request__user_id on purchase_request (user_id);

-- 5) Line items
create table purchase_request_line_item (
  id                   integer generated by default as identity,
  purchase_request_id  integer not null,
  product_id           integer not null,
  quantity             integer not null check (quantity > 0),
  constraint pk_prli primary key (id),
  constraint fk_prli__product foreign key (product_id)
    references product (id) on delete restrict,
  constraint fk_prli__pr foreign key (purchase_request_id)
    references purchase_request (id) on delete cascade
);

create index ix_prli__product_id on purchase_request_line_item (product_id);
create index ix_prli__purchase_request_id on purchase_request_line_item (purchase_request_id);
create unique index uq_prli__prid_product on purchase_request_line_item (purchase_request_id, product_id);

-- 6) Optional convenience uniques
create unique index ix_vendor__name on vendor (name);

commit;
